eureka:
    client:
        serviceUrl:
            defaultZone: http://dyb:dyb@localhost:8181/registry-center/eureka/
server:
    port: 8888
spring:
    application:
        name: springcloud-zuul
zuul:
    routes:
        api-a:
            path: /api-a/**
            serviceId: springcloud-ribbon
        api-b:
            path: /api-b/**
            serviceId: springcloud-feign