eureka:
    client:
        serviceUrl:
            defaultZone: http://dyb:dyb@localhost:8181/registry-center/eureka/
server:
    context-path: /ribbon
    port: 8980
spring:
    application:
        name: springcloud-ribbon
